### PR TITLE
Merge 4.4.151 into 8.1

### PR DESCRIPTION
**Pull request by nathanchance**

### CODE REVIEW

**Comment by Martinusbe** [comment]
Woohoo

**Comment by nathanchance** [comment]
I have Treble queued up so ping me when you want that pulled (if before 4.4.152) :)

**Comment by Martinusbe** [comment]
hmm, think i would like that on a test branch first

**Comment by nathanchance** [comment]
Done: https://github.com/nathanchance/gzr_kernel_oneplus_msm8998/tree/8.1-treble

**Pull request merged**
