### PR TITLE
Merge 4.4.144 into 8.1

### PR DESCRIPTION
**Pull request by nathanchance**

### CODE REVIEW

**Comment by nathanchance** [comment]
Ping? :)

**Comment by Martinusbe** [comment]
Yes on vacation you know 😋
I'll merge from my phone and tell one of the guys to do me a build 😎

**Comment by nathanchance** [comment]
How dare you go on vacation!

Sorry for the noise, enjoy the rest of your time off :)

**Comment by CheckYourScreen** [comment]
🤣🤣🤣🤣

**Pull request merged**
